phasetable=
{
    {
        type="MidPhase",
        time=600,
        enemytable=
        {
            {
                x=460,
                y=100,
                HP=200,
                start=240,
                End=216000,
                behaviortable=
                {
                    {
                        type="MoveToRandom1"
                    },
                    {
                        type="ScoreDrop1",
                        dropconfig=
                        {
                            droptype="Power",
                            dropnum=40
                        }
                    },
                    {
                        type="AimShoot1"
                    }
                }
            }
        }
    },

    {
        type="BossPhase",
        spelltable=
        {
            {
                time=360,
                HP=600,
                behaviortable=
                {
                    {
                        type="MoveToRandom1"
                    },

                    {
                        type="AimShoot1"
                    }
                }
            }
        }
    }
}